spring.application.name=task-manager

# Base H2 en mémoire
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Voir les requêtes SQL générées dans la console (utile pour apprendre)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Active la console web H2 (pour voir tes données dans le navigateur)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console